function result = runProcessing(app)
%RUNPROCESSING Stable PHASE StaMPS engine extracted from PHASE_StaMPS.mlapp.
% Generated by tools/extract_stamps_beta_backend.py. Edit the stable callback
% first and regenerate, or deliberately remove the generated notice when the
% beta engine is split into independent processing services.

result = struct('ok', false, 'message', '', 'identifier', '');
if ~isfolder(app.WorkDir)
    error('PHASE_StaMPS_beta:workDirMissing', ...
        'StaMPS processing folder does not exist: %s', app.WorkDir);
end
cd(app.WorkDir);
workDirCleanup = onCleanup(@() restoreWorkDir(app.WorkDir)); %#ok<NASGU>


    app.MessagesTextArea.Value = '';

    % Display a message in the UIAxes
    updateOutput(app, 'Button pressed! Running the script...');

    % Change lamp color to yellow (running)
    app.PreprocessingstatusLamp.Color = [1, 1, 0]; % Yellow

    try

        % Keep the Command Window history; the beta has its own live log.

        %% ------------------ IMPORT OF THE REQUIRED VARIABLES --------------------

        load('input_StaMPS.mat', 'stamps_preparation', 'installation_folder', 'project_path', 'amplitude_threshold', 'master_date', 'export_name', 'time_span', 'weed_time_win', 'unwrap_time_win', 'scn_time_win', ...
            'year_0', 'month_0', 'day_0', 'utc_time', 'train_flag', 'stamps_first_step', 'stamps_last_step', ...
            'n_cores', 'heading', 'lambda', 'max_topo_err', 'filter_grid_size', 'filter_weighting', ...
            'gamma_max_iterations', 'gamma_change_convergence', 'gamma_stdev_reject', 'quick_est_gamma_flag', ...
            'small_baseline_flag', 'clap_win', 'clap_alpha', 'clap_beta', 'clap_low_pass_wavelength', ...
            'select_method', 'percent_rand', 'density_rand', 'weed_standard_dev', 'weed_neighbours', 'weed_zero_elevation', ...
            'weed_max_noise', 'merge_resample_size', 'merge_standard_dev', 'unwrap_grid_size', ...
            'unwrap_gold_n_win', 'unwrap_method', 'unwrap_gold_alpha', 'unwrap_alpha', 'unwrap_spatial_cost_func_flag', ...
            'unwrap_prefilter_flag', 'unwrap_patch_phase', 'unwrap_la_error_flag', 'unwrap_hold_good_values', ...
            'subtr_tropo', 'tropo_method', 'select_reest_gamma_flag', 'drop_ifg_index', 'scla_deramp', ...
            'scla_method', 'scla_drop_index', 'scn_wavelength', 'scn_kriging_flag', 'ref_centre_lonlat', ...
            'ref_radius', 'ref_velocity', 'plot_s', 'ref_centre_lonlat_w', 'ref_radius_w', 'ph_output');

        % begin independent StaMPS temporal windows
        legacy_time_window_fields = {};
        if exist('weed_time_win', 'var') ~= 1
            weed_time_win = time_span;
            legacy_time_window_fields{end + 1} = 'weed_time_win';
        end
        if exist('unwrap_time_win', 'var') ~= 1
            unwrap_time_win = time_span;
            legacy_time_window_fields{end + 1} = 'unwrap_time_win';
        end
        if exist('scn_time_win', 'var') ~= 1
            scn_time_win = time_span;
            legacy_time_window_fields{end + 1} = 'scn_time_win';
        end
        if ~isempty(legacy_time_window_fields)
            updateOutput(app, ['Legacy input_StaMPS.mat: missing ' ...
                strjoin(legacy_time_window_fields, ', ') ...
                '; using time_span=' num2str(time_span) ...
                ' days for backward compatibility. Press Save to migrate the MAT file.']);
        end
        % end independent StaMPS temporal windows

        % begin saved/visible tropospheric-configuration guard
        % The app deliberately has separate Load and Save buttons. If
        % a user edits these controls without Save, Start would load an
        % older value, launch GACOS/seek tca2, or apply a wrong temporal window.
        % Never overwrite the MAT file here: other untouched controls
        % may still contain the app's compiled defaults until Load.
        loaded_subtr_tropo = char(string(subtr_tropo));
        visible_subtr_tropo = char(string(app.subtr_tropoEditField.Value));
        loaded_tropo_method = char(string(tropo_method));
        visible_tropo_method = char(string(app.tropo_methodEditField.Value));
        visible_train_flag = double(~app.TRAINatmosphericcorrectionCheckBox.Value);
        visible_weed_time_win = app.weed_time_winEditField.Value;
        visible_unwrap_time_win = app.unwrap_time_winEditField.Value;
        visible_scn_time_win = app.scn_time_winEditField.Value;
        % begin selected StaMPS step guard
        loaded_stamps_first_step = str2double(char(string(stamps_first_step)));
        loaded_stamps_last_step = str2double(char(string(stamps_last_step)));
        visible_stamps_first_step = str2double(char(string(app.StaMPSfirststepDropDown.Value)));
        visible_stamps_last_step = str2double(char(string(app.StaMPSlaststepDropDown.Value)));
        % end selected StaMPS step guard
        tropo_config_mismatch = ...
            ~strcmpi(strtrim(loaded_subtr_tropo), strtrim(visible_subtr_tropo)) || ...
            ~strcmpi(strtrim(loaded_tropo_method), strtrim(visible_tropo_method)) || ...
            train_flag ~= visible_train_flag;
        time_window_config_mismatch = ...
            ~isequaln(weed_time_win, visible_weed_time_win) || ...
            ~isequaln(unwrap_time_win, visible_unwrap_time_win) || ...
            ~isequaln(scn_time_win, visible_scn_time_win);
        step_range_config_mismatch = ...
            ~isequaln(loaded_stamps_first_step, visible_stamps_first_step) || ...
            ~isequaln(loaded_stamps_last_step, visible_stamps_last_step);
        if tropo_config_mismatch || time_window_config_mismatch || step_range_config_mismatch
            error('PHASE_StaMPS:unsavedConfiguration', ...
                ['The visible TRAIN/tropospheric/temporal-window/step controls do not match input_StaMPS.mat. ', ...
                 'Processing was not started and the MAT file was not changed. ', ...
                 'Press Load, make the intended changes, press Save, then press Start. ', ...
                 'Saved: TRAIN=%d, subtr_tropo=%s, tropo_method=%s, time windows=%g/%g/%g days, steps=%g->%g. ', ...
                 'Visible: TRAIN=%d, subtr_tropo=%s, tropo_method=%s, time windows=%g/%g/%g days, steps=%g->%g.'], ...
                 train_flag == 0, loaded_subtr_tropo, loaded_tropo_method, ...
                 weed_time_win, unwrap_time_win, scn_time_win, ...
                 loaded_stamps_first_step, loaded_stamps_last_step, ...
                 visible_train_flag == 0, visible_subtr_tropo, visible_tropo_method, ...
                 visible_weed_time_win, visible_unwrap_time_win, visible_scn_time_win, ...
                 visible_stamps_first_step, visible_stamps_last_step);
        end
        updateOutput(app, sprintf( ...
            ['Loaded configuration: TRAIN=%d, subtr_tropo=%s, tropo_method=%s, ', ...
             'weed/unwrap/scn time windows=%g/%g/%g days, StaMPS steps=%g->%g'], ...
            train_flag == 0, loaded_subtr_tropo, loaded_tropo_method, ...
            weed_time_win, unwrap_time_win, scn_time_win, ...
            loaded_stamps_first_step, loaded_stamps_last_step));
        clear loaded_subtr_tropo visible_subtr_tropo loaded_tropo_method
        clear visible_tropo_method visible_train_flag tropo_config_mismatch
        clear visible_weed_time_win visible_unwrap_time_win visible_scn_time_win
        clear time_window_config_mismatch legacy_time_window_fields
        clear loaded_stamps_first_step loaded_stamps_last_step
        clear visible_stamps_first_step visible_stamps_last_step
        clear step_range_config_mismatch
        % end saved/visible tropospheric-configuration guard

        % AutoDetectParameters (startupFcn) reads ground-truth values
        % from INSAR_<date>/diff0/*.diff.par and LOCKS the relevant GUI
        % fields (heading, lambda, master_date, year/month/day,
        % time_span, utc_time). When that succeeds, the GUI is the
        % authoritative source and we MUST override the .mat values:
        % the .mat may carry installer-precompiled placeholders or
        % stale values from a previous project, which would otherwise
        % break mt_prep_snap / ps_load_initial_gamma downstream.
        if isprop(app, 'headingEditField') && strcmp(app.headingEditField.Enable, 'off')
            heading = app.headingEditField.Value;
        end
        if isprop(app, 'lambdaEditField') && strcmp(app.lambdaEditField.Enable, 'off')
            lambda = app.lambdaEditField.Value;
        end
        if isprop(app, 'MasterdateDatePicker') && strcmp(app.MasterdateDatePicker.Enable, 'off')
            master_date = app.master_date;
        end
        if isprop(app, 'DateDatePicker') && strcmp(app.DateDatePicker.Enable, 'off')
            year_0  = app.year_0;
            month_0 = app.month_0;
            day_0   = app.day_0;
        end
        if isprop(app, 'DaysEditField') && strcmp(app.DaysEditField.Enable, 'off')
            time_span = app.DaysEditField.Value;
        end
        if isprop(app, 'TimeEditField') && strcmp(app.TimeEditField.Enable, 'off')
            utc_time = app.TimeEditField.Value;
        end

        train_requested = (train_flag == 0) && strcmpi(strtrim(subtr_tropo), 'y');
        % begin TRAIN availability check (Windows port, cross-platform no-op
        % when TRAIN is correctly installed). Multi-function probe
        % avoids false positives from unrelated aps_linear.m on path
        % or incomplete installs. On miss, degrade silently using a
        % LOCAL train_flag override — do not touch app.train_flag nor
        % the checkbox, so the user's original intent is preserved
        % for the next run (they can install TRAIN and press Start
        % again without re-ticking the box).
        train_available = ~isempty(which('aps_linear')) && ...
                          ~isempty(which('aps_weather_model')) && ...
                          ~isempty(which('setparm_aps'));
        if train_flag == 0 && ~train_available
            warning('StaMPS:phase:trainNotAvailable', '%s', ...
                ['TRAIN not found on MATLAB path (or install is incomplete). ', ...
                 'Install TRAIN (e.g. git clone https://github.com/dbekaert/TRAIN.git) ', ...
                 'then in MATLAB: addpath(genpath(''<TRAIN>/matlab'')); savepath. ', ...
                 'Proceeding without atmospheric correction.']);
            train_flag = 1;
        end
        % end TRAIN availability check

        % begin TRAIN interactive recovery (Windows-port UX). If the user
        % asked for the correction (train_flag was 0) but TRAIN is not on
        % the path, offer a folder picker to locate it and fix the run on
        % the fly, instead of silently proceeding without correction.
        if train_requested && ~train_available
            reco_choice = uiconfirm(app.UIFigure, ...
                ['TRAIN was not found on the MATLAB path, so the tropospheric correction (' tropo_method ') cannot run. ', ...
                 'Locate your TRAIN folder now to fix it, or skip the correction for this run.'], ...
                'TRAIN not found', ...
                'Options', {'Locate TRAIN folder...', 'Skip correction'}, ...
                'DefaultOption', 1, 'CancelOption', 2);
            if strcmp(reco_choice, 'Locate TRAIN folder...')
                while true
                    train_dir = uigetdir('', 'Select your TRAIN folder (the one containing the "matlab" subfolder)');
                    if isequal(train_dir, 0)
                        updateOutput(app, 'TRAIN selection cancelled - proceeding without atmospheric correction.');
                        break
                    end
                    if exist(fullfile(train_dir, 'matlab'), 'dir') == 7
                        train_matlab = fullfile(train_dir, 'matlab');
                    else
                        train_matlab = train_dir;
                    end
                    addpath(genpath(train_matlab));
                    train_available = ~isempty(which('aps_linear')) && ...
                                      ~isempty(which('aps_weather_model')) && ...
                                      ~isempty(which('setparm_aps'));
                    if train_available
                        train_flag = 0;
                        updateOutput(app, ['TRAIN located and enabled for this run: ' train_matlab]);
                        persist_choice = uiconfirm(app.UIFigure, ...
                            'TRAIN added for this session. Make it permanent so you do not have to locate it every time?', ...
                            'TRAIN located', ...
                            'Options', {'Make permanent', 'Just this session'}, ...
                            'DefaultOption', 1, 'CancelOption', 2);
                        if strcmp(persist_choice, 'Make permanent')
                            if savepath ~= 0
                                up = userpath;
                                if isempty(up)
                                    up = fullfile(char(java.lang.System.getProperty('user.home')), 'Documents', 'MATLAB');
                                end
                                if exist(up, 'dir') == 0
                                    mkdir(up);
                                end
                                fid_su = fopen(fullfile(up, 'startup.m'), 'a');
                                if fid_su ~= -1
                                    fprintf(fid_su, '\naddpath(genpath(''%s''));\n', strrep(train_matlab, '\', '/'));
                                    fclose(fid_su);
                                    updateOutput(app, ['TRAIN path saved to ' fullfile(up, 'startup.m') ' - it will load at every MATLAB start.']);
                                end
                            else
                                updateOutput(app, 'TRAIN path saved permanently (savepath).');
                            end
                        end
                        break
                    else
                        retry_choice = uiconfirm(app.UIFigure, ...
                            ['That folder does not contain TRAIN (aps_linear / aps_weather_model / setparm_aps were not found under it). ', ...
                             'Choose a different folder, or skip the correction?'], ...
                            'Not a TRAIN folder', ...
                            'Options', {'Choose again...', 'Skip correction'}, ...
                            'DefaultOption', 1, 'CancelOption', 2);
                        if strcmp(retry_choice, 'Skip correction')
                            updateOutput(app, 'Proceeding without atmospheric correction.');
                            break
                        end
                    end
                end
            else
                updateOutput(app, 'Proceeding without atmospheric correction (user chose to skip).');
            end
        end
        % end TRAIN interactive recovery

        % begin effective tropospheric-correction decision
        % TRAIN-dependent preparation, processing and export must all
        % agree. Checking train_flag alone made a subtr_tropo='n' run
        % attempt to export tca2.mat even though no correction existed.
        tropo_correction_enabled = (train_flag == 0) && ...
            strcmpi(strtrim(subtr_tropo), 'y');
        if train_flag == 0 && ~tropo_correction_enabled
            updateOutput(app, ['Tropospheric correction disabled by ', ...
                'subtr_tropo=' char(string(subtr_tropo)) '.']);
        end
        % end effective tropospheric-correction decision

        % Conversion of variables' format
        if isa(master_date, 'datetime')
            master_date = datestr(master_date, 'yyyymmdd');
        end
        if strcmp(drop_ifg_index, '[]')
            drop_ifg_index = [];
        else
            drop_ifg_index = str2double(strsplit(drop_ifg_index));
        end
        if strcmp(scla_drop_index, '[]')
            scla_drop_index = [];
        else
            scla_drop_index = str2double(strsplit(scla_drop_index));
        end

        %% -- PREPARATION OF THE SNAP2STAMPS EXPORTED DATA FOR STAMPS PROCESSING --

        % PATH DESCRIPTIONS
        cd_fullpath = cd; % folder in which this code is located
        addpath(genpath(installation_folder));
        % Ensure StaMPS native binaries (snaphu, triangle, calamp, ...) are on the
        % process PATH for system() calls, even if the app was launched without the
        % install-folder field set at startup (startupFcn only adds them when set).
        bin_paths = {fullfile(installation_folder,'bin'), fullfile(installation_folder,'external','triangle','bin'), fullfile(installation_folder,'external','snaphu','bin')};
        path_segments = strsplit(getenv('PATH'), pathsep);
        for k = 1:numel(bin_paths)
            if isfolder(bin_paths{k}) && ~any(strcmpi(path_segments, bin_paths{k}))
                setenv('PATH', [bin_paths{k}, pathsep, getenv('PATH')]);
            end
        end
        if isunix
            stamps_path = which('StaMPS_CONFIG.bash');
        else
            stamps_path = which('StaMPS_CONFIG.ps1');
        end
        s2s_export_path = strcat(project_path, '/PHASE_Preprocessing/INSAR_', master_date);
        mt_prep_snap = ('mt_prep_snap');
        source = ('source');
        space = (' ');
        amplitude_threshold = (num2str(amplitude_threshold));
        stamps_first_step = str2double(stamps_first_step);
        stamps_last_step = str2double(stamps_last_step);

        % DEFINITION OF THE TASKS
        source_stamps = [source space stamps_path];
        source_stamps = strcat(source_stamps, ' -echo');
        source_snap = [mt_prep_snap space master_date space s2s_export_path space amplitude_threshold];

        % EXECUTION OF THE TASKS
        if stamps_preparation == 0 % check if the StaMPS preparation has to be done or not

            updateOutput(app, '----------------------- STEP 1: Data preparation started -----------------------');

            if isfolder(strcat(cd_fullpath, '/PATCH_1'))
               elements_struct = dir(cd_fullpath); % list all elements in the processing folder
               elements_cell = struct2cell(elements_struct); % convert from structure to cell
               elements_cell_name = elements_cell(1,3:end); %take only the file names
               logic_stamps = contains(elements_cell_name, 'StaMPS'); % find elements with name StaMPS
               logic_patch = contains(elements_cell_name, 'PATCH_'); % find folder(s) PATCH
               logic_calamp = contains(elements_cell_name, 'calamp'); % find elements with name calamp
               logic_len = contains(elements_cell_name, 'len'); % find elements with name len
               logic_parms = contains(elements_cell_name, 'parms.mat'); % find elements with name parms.mat
               logic_patch_list = contains(elements_cell_name, 'patch.list'); % find elements with name patch.list
               logic_processor = contains(elements_cell_name, 'processor.txt'); % find elements with name processor.txt
               logic_psparms = contains(elements_cell_name, 'ps_parms_initial.log'); % find elements with name ps_parms_initial.log
               logic_psc = contains(elements_cell_name, 'psc'); % find elements with name psc
               logic_rsc = contains(elements_cell_name, 'rsc.txt'); % find elements with name rsc.txt
               logic_selpsc = contains(elements_cell_name, 'selpsc.txt'); % find elements with name selpsc.txt
               logic_width = contains(elements_cell_name, 'width.txt'); % find elements with name width.txt
               logic_export = contains(elements_cell_name, 'EXPORT'); % find folder with name EXPORT
               logic_all = logic_stamps + logic_patch + logic_calamp + logic_len + logic_parms ...
                   + logic_patch_list + logic_processor + logic_psparms + logic_psc + logic_rsc + logic_selpsc + logic_width + logic_export;
               for i = 1:length(logic_all)
                   if logic_all(i) == 0
                       builtin('delete', (char(strcat(cd_fullpath, '/', elements_cell_name(i))))); % delete the previous-execution elements
                   end
               end
            end

            if tropo_correction_enabled % TRAIN correction is effectively enabled
                if isunix
    train_path = which('APS_CONFIG.sh');
else
    train_path = '';   % Windows: TRAIN on MATLABPATH, no shell config to source
end
                source_train = [source space train_path];
                if isunix
    phase_stamps_beta.runCommandHidden(app, strjoin({source_stamps, source_train, source_snap}, ';'), 'StaMPS, TRAIN and SNAP environment preparation');
else
    [mt_prep_snap_status, mt_prep_snap_output] = ...
    phase_stamps_beta.runCommandHidden(app, ...
        {which('mt_prep_snap.bat'), master_date, s2s_export_path, amplitude_threshold}, ...
        'StaMPS data preparation');
    if mt_prep_snap_status ~= 0
error('PHASE_StaMPS:mtPrepSnapFailed', ...
      'mt_prep_snap failed (exit code %d). Check the PHASE Run monitor above for the cause (commonly: a previous MATLAB session is still holding files in PATCH_* — close it and retry).', ...
      mt_prep_snap_status);
    end
end % source all the softwares and prepare the data
            else
                if isunix
    phase_stamps_beta.runCommandHidden(app, strjoin({source_stamps, source_snap}, ';'), 'StaMPS and SNAP environment preparation');
else
    [mt_prep_snap_status, mt_prep_snap_output] = ...
    phase_stamps_beta.runCommandHidden(app, ...
        {which('mt_prep_snap.bat'), master_date, s2s_export_path, amplitude_threshold}, ...
        'StaMPS data preparation');
    if mt_prep_snap_status ~= 0
error('PHASE_StaMPS:mtPrepSnapFailed', ...
      'mt_prep_snap failed (exit code %d). Check the PHASE Run monitor above for the cause (commonly: a previous MATLAB session is still holding files in PATCH_* — close it and retry).', ...
      mt_prep_snap_status);
    end
end % source all the softwares and prepare the data
            end

            if isfolder(strcat(cd_fullpath, '/EXPORT')) == 0
                mkdir('EXPORT');
            end

            updateOutput(app, '----------------------- STEP 1: Data preparation finished -----------------------');

        else

            if tropo_correction_enabled % TRAIN correction is effectively enabled
                train_path = which('APS_CONFIG.sh');
                source_train = [source space train_path];
                if isunix
    phase_stamps_beta.runCommandHidden(app, strjoin({source_stamps, source_train}, ';'), 'StaMPS and TRAIN environment preparation');
else
    % Windows: when train_flag==0 reaches here, Change #1 has already
    % verified TRAIN is on MATLABPATH; no shell config to source.
end % source all the softwares and prepare the data
            else
                if isunix
    phase_stamps_beta.runCommandHidden(app, source_stamps, 'StaMPS environment preparation');
else
    % Environment comes from self-bootstrapping .bat shim
end % source all the softwares and prepare the data
            end

            updateOutput(app, '---------------------- STEP1: Data preparation skipped -----------------------');

        end

        % Safely delete previous export files if they exist
        csv_path = fullfile(cd_fullpath, 'EXPORT', [export_name, '.csv']);
        if exist(csv_path, 'file') == 2
            builtin('delete', csv_path);
        end

        xlsx_path = fullfile(cd_fullpath, 'EXPORT', [export_name, '.xlsx']);
        if exist(xlsx_path, 'file') == 2
            builtin('delete', xlsx_path);
        end

        %% ---------------- DEFINITION OF THE REQUIRED VARIABLES ------------------

        % INPUT VARIABLES
        D = datetime(year_0,month_0,day_0,0,0,0);  % first date of the time series
        time_zero_nf = convertTo(D, 'yyyymmdd'); % date conversion
        time_zero = convertTo(D, 'datenum'); % date conversion

        % STAMPS PARAMETERS DEFINITION
        % Step 1 - Load Data
        setparm('heading', heading); % satellite heading wrt north (deg)
        setparm('n_cores', n_cores); % n° of cores to be used for the processing
        % Step 2 - Estimate Phase Noise
        setparm('max_topo_err', max_topo_err); % max uncorrelated DEM error (m)
        setparm('filter_grid_size', filter_grid_size); % pixel size of resampling grid
        setparm('filter_weighting', filter_weighting); % weighting scheme
        setparm('gamma_max_iterations', gamma_max_iterations); % maximum number of iterations
        setparm('gamma_change_convergence', gamma_change_convergence); % threshold for change in mean value of coherence
        setparm('gamma_stdev_reject', gamma_stdev_reject);
        setparm('quick_est_gamma_flag', quick_est_gamma_flag); % quick estimation of gamma (coherence)
        setparm('small_baseline_flag', small_baseline_flag);
        setparm('clap_win', clap_win); % CLAP filter window size
        setparm('clap_alpha', clap_alpha); % CLAP filter alpha term
        setparm('clap_beta', clap_beta); % CLAP filter beta term
        setparm('clap_low_pass_wavelength', clap_low_pass_wavelength); % CLAP filter spatial wavelength cutoff (m)
        % Step 3 - PS Selection
        setparm('select_method', select_method); % selection method for pixels with random phase, alternative 'DENSITY'
        if strcmpi(select_method, 'DENSITY')
            setparm('density_rand', density_rand); % maximum random PS density
        else
            setparm('percent_rand', percent_rand); % maximum acceptable percentage, alternative 'density_rand'
        end
        % Step 4 - PS Weeding
        setparm('weed_time_win', weed_time_win); % smoothing window (days)
        setparm('weed_standard_dev', weed_standard_dev); % threshold standard deviation
        setparm('weed_neighbours', weed_neighbours); % flag for proximity weeding
        setparm('weed_zero_elevation', weed_zero_elevation); % flag for zero elevation weeding
        setparm('weed_max_noise', weed_max_noise); % threshold for the maximum noise allowed for a pixel
        % Step 5 - Phase Correction
        setparm('merge_resample_size', merge_resample_size); % coarser posting to resample to (m), 0 = no resampling is applied
        setparm('merge_standard_dev', merge_standard_dev); % threshold standard deviation for resampling
        % Step 6 - Phase Unwrapping
        setparm('unwrap_grid_size', unwrap_grid_size); % resampling grid spacing
        setparm('unwrap_gold_n_win', unwrap_gold_n_win); % window size for Goldstein filter
        setparm('unwrap_time_win', unwrap_time_win); % smoothing window for phase noise distribution (days)
        setparm('unwrap_method', unwrap_method); % unwrapping method
        setparm('unwrap_gold_alpha', unwrap_gold_alpha); % value of alpha for Goldstein filter
        setparm('unwrap_alpha', unwrap_alpha);
        setparm('unwrap_spatial_cost_func_flag', unwrap_spatial_cost_func_flag);
        setparm('unwrap_prefilter_flag', unwrap_prefilter_flag); % prefilter phase before unwrapping to reduce noise
        setparm('unwrap_patch_phase', unwrap_patch_phase); % use the patch phase of step 3 as prefiltered phase
        setparm('unwrap_la_error_flag', unwrap_la_error_flag); % flag for look angle
        setparm('unwrap_hold_good_values', unwrap_hold_good_values);
        setparm('subtr_tropo', subtr_tropo); % subtract tropospheric effect (TRAIN)
        setparm('tropo_method', tropo_method); % method for tropospheric correction (TRAIN)
        setparm('select_reest_gamma_flag', select_reest_gamma_flag);
        setparm('drop_ifg_index', drop_ifg_index); % remove selected interferograms
        % Step 7 - Estimate Spatially Correlated Look Angle Error
        setparm('scla_deramp', scla_deramp); % flag for phase ramp estimation
        setparm('scla_method', scla_method); % scla method
        setparm('scla_drop_index', scla_drop_index); % remove selected interferograms from step 7 & 8
        % Step 8 - Atmospheric Filtering
        setparm('scn_wavelength', scn_wavelength); % spatial filter
        setparm('scn_time_win', scn_time_win); % temporal filter (days)
        setparm('scn_kriging_flag', scn_kriging_flag);
        % Plots
        setparm('ref_centre_lonlat', ref_centre_lonlat); % deg coordinates of the centre of AOI
        setparm('ref_radius', ref_radius); % radius in m
        setparm('ref_velocity', ref_velocity); % reference velocity for plot
        setparm('plot_s', plot_s); % dimension of PS pixels in the plot

        % UPDATE PARMS.MAT IN CASE OF NANs
        heading1_tmp = heading;
        lambda_tmp = lambda;
        load('parms.mat');
        if isnan(heading)
            heading = heading_tmp;
        end
        if isnan(lambda)
            lambda = lambda_tmp;
        end
        save('parms.mat', 'heading', 'lambda', '-append');
        clear heading_tmp
        clear lambda_tmp


        %% -------------------------- RUN STAMPS ----------------------------------

        updateOutput(app, '----------------------- STEP 2: StaMPS processing started -----------------------');

        % begin Windows StaMPS step-6 preflight
        % The old Windows ps_unwrap branch calls uw_nosnaphu.  Its
        % sparse-graph solver can loop forever without raising an error,
        % which looks exactly like a frozen PHASE app.  Refuse that stale
        % implementation and verify the maintained snaphu path up front.
        if contains(ph_output, 'unwrapped') && stamps_last_step >= 6
            ps_unwrap_impl = which('ps_unwrap');
            if isempty(ps_unwrap_impl)
                error('PHASE_StaMPS:psUnwrapMissing', ...
                    ['ps_unwrap.m was not found. Check the StaMPS installation ', ...
                     'folder selected in PHASE: %s'], installation_folder);
            end

            if ispc
                ps_unwrap_src = fileread(ps_unwrap_impl);
                old_unwrap_call = regexp(ps_unwrap_src, ...
                    '(?m)^\s*\[ph_uw_some\]\s*=\s*uw_nosnaphu\s*\(', 'once');
                if ~isempty(old_unwrap_call)
                    error('PHASE_StaMPS:staleWindowsPsUnwrap', ...
                        ['PHASE resolved an obsolete Windows ps_unwrap.m that is known ', ...
                         'to loop indefinitely during step 6: %s. Update/reinstall the ', ...
                         'pyccino/StaMPS master fork and make that folder the StaMPS ', ...
                         'installation folder in PHASE.'], ps_unwrap_impl);
                end

                uw_stat_impl = which('uw_stat_costs');
                if isempty(uw_stat_impl)
                    error('PHASE_StaMPS:uwStatCostsMissing', ...
                        'uw_stat_costs.m was not found below the selected StaMPS installation.');
                end
                uw_stat_src = fileread(uw_stat_impl);
                unix_redirect_call = regexp(uw_stat_src, ...
                    '(?m)^\s*cmdstr\s*=.*>&\s*snaphu\.log', 'once');
                if ~isempty(unix_redirect_call)
                    error('PHASE_StaMPS:staleWindowsUwStatCosts', ...
                        ['PHASE resolved an obsolete uw_stat_costs.m containing a ', ...
                         'Unix-only snaphu command: %s. Update/reinstall the ', ...
                         'pyccino/StaMPS master fork.'], uw_stat_impl);
                end

                [snaphu_status, snaphu_where] = phase_stamps_beta.runCommandHidden( ...
                    app, {'where','snaphu'}, 'snaphu lookup');
                if snaphu_status ~= 0 || isempty(strtrim(snaphu_where))
                    expected_snaphu = fullfile(installation_folder, ...
                        'external', 'snaphu', 'bin', 'snaphu.exe');
                    error('PHASE_StaMPS:snaphuMissing', ...
                        ['snaphu.exe is not available on PATH, so StaMPS step 6 ', ...
                         'cannot unwrap safely on Windows. Expected installer output: ', ...
                         '%s. Re-run the PHASE installer or restore the native StaMPS ', ...
                         'binaries before retrying.'], expected_snaphu);
                end

                resolved_snaphu = regexprep(strtrim(snaphu_where), '[\r\n]+', '; ');
                updateOutput(app, ['Step 6 preflight: ps_unwrap = ' ps_unwrap_impl]);
                updateOutput(app, ['Step 6 preflight: snaphu = ' resolved_snaphu]);
            end

            updateOutput(app, ['Step 6 preflight passed. Phase unwrapping can take ', ...
                'a long time; progress is mirrored live in the PHASE Run monitor as ', ...
                '''Processing IFG x of y''.']);
            drawnow;
            clear ps_unwrap_impl ps_unwrap_src old_unwrap_call uw_stat_impl
            clear uw_stat_src unix_redirect_call snaphu_status snaphu_where
            clear expected_snaphu resolved_snaphu
        end
        % end Windows StaMPS step-6 preflight

        if contains(ph_output, 'unwrapped')
            % TRAIN is usable only when both controls request correction.
            if tropo_correction_enabled
                if stamps_first_step <= 6
                    % Guard: a stale tca<psver>.mat from a different tropo_method makes step 6
                    % (ps_unwrap with subtr_tropo='y') fail looking for ph_tropo_<method>.
                    % Drop it so the correct correction is recomputed by this run.
                    if exist('psver.mat', 'file') == 2
                        psver_tmp = load('psver.mat');
                        tca_file = sprintf('tca%d.mat', psver_tmp.psver);
                        if exist(tca_file, 'file') == 2
                            method_field = ['ph_tropo_' strrep(tropo_method, 'a_', '')];
                            if ~ismember(method_field, who('-file', tca_file))
                                delete(tca_file);
                                updateOutput(app, ['Removed stale ' tca_file ' (incompatible with tropo_method=' tropo_method ').']);
                            end
                        end
                        clear psver_tmp
                    end
                    stamps(stamps_first_step,6); % execute StaMPS steps from first step to 6

                    if contains(tropo_method, 'a_linear')

                        aps_linear; % to apply the TRAIN tropospheric correction

                    elseif contains(tropo_method, 'a_gacos')

                        mkdir(strcat(cd, '/GACOS'));
                        setparm_aps('gacos_datapath', strcat(cd, '/GACOS'));
                        setparm_aps('UTC_sat', utc_time);
                        aps_weather_model('gacos', 0, 0);

                        if exist('gacos_maps', 'dir') == 0

                            % Clearer instructions regarding multiple files
                            instructions = ['Go to www.gacos.net and request atmospheric delay maps using the data in "GACOS_download_info.txt". ', ...
                                            'GACOS limits requests to 20 dates. If you have more, make multiple requests. ', ...
                                            'Place ALL the downloaded compressed folders (.tar.gz) directly into the "GACOS" folder. ', ...
                                            'Do not extract them. Once all files are in place, press "Continue" in the dialog box to resume.'];
                            updateOutput(app, instructions);

                            % --- Manual GACOS download (no debug 'keyboard') ---
                            % Open the GACOS website and the destination folder, then BLOCK on a
                            % modal dialog until the user has placed the .tar.gz archives. Replaces
                            % the old `keyboard` so the run never drops into MATLAB debug mode.
                            gacosFolder = fullfile(cd, 'GACOS');
                            try, web('http://www.gacos.net', '-browser'); catch, end
                            try, winopen(gacosFolder); catch, end
                            while true
                                gacos_choice = gacosDownloadDialog();
                                if strcmp(gacos_choice, 'Cancel')
                                    updateOutput(app, 'GACOS download cancelled by user. No atmospheric correction applied.');
                                    if exist('cd_fullpath', 'var') && ~isempty(cd_fullpath) && isfolder(cd_fullpath)
                                        cd(cd_fullpath);
                                    end
                                    app.PreprocessingstatusLamp.Color = [1, 0, 0];
                                    return
                                end
                                if isempty(dir(fullfile(gacosFolder, '*.tar.gz')))
                                    uialert(app.UIFigure, ...
                                        'No .tar.gz files found in the GACOS folder yet. Place them and press Continue.', ...
                                        'GACOS files missing');
                                else
                                    break
                                end
                            end

                            % Define main paths
                            gacosFolder = fullfile(cd, 'GACOS');
                            gacosMapsFolder = fullfile(cd, 'gacos_maps');
                            mkdir(gacosMapsFolder);

                            % Find all .tar.gz files injected by the user
                            gzFiles = dir(fullfile(gacosFolder, '*.tar.gz'));

                            if isempty(gzFiles)
                                updateOutput(app, 'Warning: No .tar.gz files found in the GACOS folder! GACOS corrections will fail.');
                            else
                                updateOutput(app, sprintf('Found %d GACOS .tar.gz file(s). Extracting and sorting...', length(gzFiles)));

                                % 1. Extract all archives
                                for k = 1:length(gzFiles)
                                    gzFilePath = fullfile(gacosFolder, gzFiles(k).name);
                                    tempUnzipDir = fullfile(gacosFolder, sprintf('temp_unzip_%d', k));

                                    % gunzip the .tar.gz
                                    gunzip(gzFilePath, tempUnzipDir);

                                    % untar the resulting .tar directly into the shared gacos_maps folder
                                    tarFiles = dir(fullfile(tempUnzipDir, '*.tar'));
                                    if ~isempty(tarFiles)
                                        tarFilePath = fullfile(tempUnzipDir, tarFiles(1).name);
                                        untar(tarFilePath, gacosMapsFolder);
                                    end

                                    % Cleanup temp folder and original archive
                                    rmdir(tempUnzipDir, 's');
                                    builtin('delete', gzFilePath);
                                end

                                % 2. Distribute the extracted files into their respective date folders
                                % We specifically look for .ztd files, making this immune to hidden OS files
                                ztdFiles = dir(fullfile(gacosMapsFolder, '*.ztd'));

                                for k = 1:length(ztdFiles)
                                    % Extract the date from the filename (e.g., '20200305' from '20200305.ztd')
                                    [~, dateStr, ~] = fileparts(ztdFiles(k).name);

                                    ztdSource = fullfile(gacosMapsFolder, [dateStr, '.ztd']);
                                    rscSource = fullfile(gacosMapsFolder, [dateStr, '.ztd.rsc']);

                                    ztdDest = fullfile(gacosFolder, dateStr, [dateStr, '.ztd']);
                                    rscDest = fullfile(gacosFolder, dateStr, [dateStr, '.ztd.rsc']);

                                    % Only move if TRAIN successfully created the target date folder
                                    if exist(fullfile(gacosFolder, dateStr), 'dir') == 7
                                        movefile(ztdSource, ztdDest);
                                        if exist(rscSource, 'file') == 2
                                            movefile(rscSource, rscDest);
                                        end
                                    else
                                        updateOutput(app, ['Warning: Target folder GACOS/', dateStr, ' does not exist. Skipping file.']);
                                    end
                                end

                                updateOutput(app, 'GACOS maps successfully extracted and allocated.');
                            end
                        end

                        setparm_aps('lambda', lambda, 1);
                        setparm_aps('heading', heading, 1);
                        % TRAIN derives its InSAR output path from pwd.  Force the
                        % processing root so tca<psver>.mat cannot be written elsewhere.
                        cd(cd_fullpath);
                        aps_weather_model('gacos', 3, 3);
                        cd(cd_fullpath);

                    end

                    % begin TRAIN/TCA handoff guard
                    % ps_calc_scla (StaMPS step 7) loads ./tca<psver> as soon as
                    % subtr_tropo='y'.  Validate TRAIN's output here so a missing or
                    % incompatible correction never reaches that opaque load() call.
                    psver_tca = load(fullfile(cd_fullpath, 'psver.mat'), 'psver');
                    if strcmpi(strtrim(small_baseline_flag), 'y')
                        tca_name = sprintf('tca_sb%d.mat', psver_tca.psver);
                    else
                        tca_name = sprintf('tca%d.mat', psver_tca.psver);
                    end
                    tca_path = fullfile(cd_fullpath, tca_name);
                    tca_field = ['ph_tropo_' regexprep(strtrim(tropo_method), '^a_', '')];
                    if exist(tca_path, 'file') ~= 2
                        error('PHASE_StaMPS:gacosTcaMissing', ...
                            ['TRAIN finished without creating %s. StaMPS step 7 cannot ', ...
                             'apply tropo_method=%s without this file. aps_weather_model_InSAR ', ...
                             'resolved to: %s'], tca_path, tropo_method, ...
                             which('aps_weather_model_InSAR'));
                    end
                    tca_vars = who('-file', tca_path);
                    if ~ismember(tca_field, tca_vars)
                        error('PHASE_StaMPS:gacosTcaInvalid', ...
                            ['%s exists, but does not contain %s for tropo_method=%s. ', ...
                             'Restart PHASE at StaMPS step 6 to rebuild the correction.'], ...
                             tca_path, tca_field, tropo_method);
                    end
                    updateOutput(app, ['TRAIN correction ready for StaMPS step 7: ' tca_path]);
                    clear psver_tca tca_name tca_path tca_field tca_vars
                    % end TRAIN/TCA handoff guard

                    stamps(7,7); % execute StaMPS step 7
                    stamps(6,stamps_last_step); % subtract the computed corrections before the phase unwrapping
                else
                    % begin resumed TRAIN/TCA handoff guard
                    % A run resumed at step 7 used to assume that tca<psver>.mat was
                    % already present.  Rebuild a missing/incompatible GACOS correction
                    % from the staged .ztd maps before entering StaMPS.
                    cd(cd_fullpath);
                    psver_tca = load(fullfile(cd_fullpath, 'psver.mat'), 'psver');
                    if strcmpi(strtrim(small_baseline_flag), 'y')
                        tca_name = sprintf('tca_sb%d.mat', psver_tca.psver);
                    else
                        tca_name = sprintf('tca%d.mat', psver_tca.psver);
                    end
                    tca_path = fullfile(cd_fullpath, tca_name);
                    tca_field = ['ph_tropo_' regexprep(strtrim(tropo_method), '^a_', '')];
                    tca_vars = {};
                    if exist(tca_path, 'file') == 2
                        tca_vars = who('-file', tca_path);
                    end

                    if (exist(tca_path, 'file') ~= 2 || ~ismember(tca_field, tca_vars)) && ...
                            contains(tropo_method, 'a_gacos')
                        gacosFolder = fullfile(cd_fullpath, 'GACOS');
                        gacosZtd = dir(fullfile(gacosFolder, '**', '*.ztd'));
                        if isempty(gacosZtd)
                            error('PHASE_StaMPS:gacosMapsMissing', ...
                                ['Cannot rebuild %s: no GACOS .ztd maps were found below %s. ', ...
                                 'Restart PHASE at StaMPS step 6 to download/import them.'], ...
                                 tca_path, gacosFolder);
                        end
                        updateOutput(app, ['Rebuilding missing GACOS correction before StaMPS step 7: ' tca_path]);
                        setparm_aps('gacos_datapath', gacosFolder);
                        setparm_aps('UTC_sat', utc_time);
                        setparm_aps('lambda', lambda, 1);
                        setparm_aps('heading', heading, 1);
                        cd(cd_fullpath);
                        aps_weather_model('gacos', 3, 3);
                        cd(cd_fullpath);
                    end

                    if exist(tca_path, 'file') ~= 2
                        error('PHASE_StaMPS:gacosTcaMissing', ...
                            ['StaMPS step 7 needs %s for tropo_method=%s, but TRAIN did ', ...
                             'not create it. aps_weather_model_InSAR resolved to: %s'], ...
                             tca_path, tropo_method, which('aps_weather_model_InSAR'));
                    end
                    tca_vars = who('-file', tca_path);
                    if ~ismember(tca_field, tca_vars)
                        error('PHASE_StaMPS:gacosTcaInvalid', ...
                            ['%s does not contain %s. Restart PHASE at StaMPS step 6 ', ...
                             'to rebuild the selected atmospheric correction.'], ...
                             tca_path, tca_field);
                    end
                    updateOutput(app, ['TRAIN correction ready for resumed StaMPS processing: ' tca_path]);
                    clear psver_tca tca_name tca_path tca_field tca_vars gacosFolder gacosZtd
                    % end resumed TRAIN/TCA handoff guard

                    stamps(stamps_first_step, stamps_last_step);
                    stamps(6,stamps_last_step); % subtract the computed corrections before the phase unwrapping
                end
            else
                % begin TRAIN-degradation GUI notice (surfaces the otherwise-silent
                % subtr_tropo='n' reset; mirrors the Command Window warning above so
                % the user is not left thinking the requested correction actually ran).
                if ~train_available && strcmpi(subtr_tropo, 'y')
                    updateOutput(app, ['NOTE: TRAIN was not found on the MATLAB path, so the requested ', ...
                        'tropospheric correction (subtr_tropo=y, tropo_method=', tropo_method, ') is being ', ...
                        'SKIPPED and subtr_tropo is forced to ''n'' for this run. To enable it, run ', ...
                        'which(''aps_weather_model'') in MATLAB: if it is empty, add TRAIN with ', ...
                        'addpath(genpath(''<TRAIN>/matlab'')); savepath, then press Start again. ', ...
                        'For tropo_method=a_gacos also install GMT and make sure ''gmt --version'' works.']);
                end
                % end TRAIN-degradation GUI notice
                setparm('subtr_tropo', 'n');
                stamps(stamps_first_step, stamps_last_step); % execute the complete range selected in the GUI
            end

        elseif contains(ph_output, 'wrapped')
            ref_centre_lonlat = ref_centre_lonlat_w;
            stamps(stamps_first_step,5)
        end

        updateOutput(app, '----------------------- STEP 2: StaMPS processing finished -----------------------');


        %% ----------------------- EXPORT THE RESULTS -----------------------------

        if stamps_last_step > 6 && contains(ph_output, 'unwrapped')

            updateOutput(app, '----------------------- STEP 3: Displacement time series export started -----------------------');

            % LEGACY EXPORT: produces a single XLSX/CSV with every
            % PS for the AOI. Granular point selection on a basemap
            % is now handled by the TS Points tab (uses
            % ts_export_picker on top of ps_plot_ts_<vt>.mat).
            %
            % Historically this block opened an interactive figure
            % via ps_plot(...,'ts'), paused on `keyboard`, and asked
            % the user to click a centre + radius before continuing.
            % That manual step has been removed: it stalled the
            % run when the user didn't notice the K>> prompt, and
            % the TS Points tab covers point-level export better.
            % ps_plot needs to be called twice: once with 'ts' to produce
            % ps_plot_ts_<vt>.mat (the per-PS time-series matrix used
            % below), and once with -1 to produce ps_plot_v[-d]a-o.mat
            % (the per-PS velocity vector). The 'ts' call opens a
            % background figure even with BACKGROUND=1; we capture and
            % delete it so the run stays non-interactive.
            if tropo_correction_enabled % TRAIN tropo correction included
                load parms.mat;
                fig_before = findall(0, 'Type', 'figure');
                evalc("ps_plot('v-dao', tropo_method, 'ts', 1)");
                new_figs = setdiff(findall(0, 'Type', 'figure'), fig_before);
                if ~isempty(new_figs); delete(new_figs); end
                ps_plot('v-dao', tropo_method, -1);   % write ps_plot_v-dao.mat
                load ps_plot_v-dao.mat;
                loaded_ps_ts = load('ps_plot_ts_v-dao.mat');
                new_days_name = 'day_var';
                eval([new_days_name ' = loaded_ps_ts.day;']);
                load('ps_plot_ts_v-dao.mat', 'bperp', 'ifg_list', 'lambda', 'lonlat', 'master_day', 'n_ps', 'ph_mm', 'ref_ps', 'unwrap_ifg_index');
            else % no TRAIN
                load parms.mat;
                fig_before = findall(0, 'Type', 'figure');
                evalc("ps_plot('v-do', 'ts', 1)");
                new_figs = setdiff(findall(0, 'Type', 'figure'), fig_before);
                if ~isempty(new_figs); delete(new_figs); end
                ps_plot('v-do', -1);                  % write ps_plot_v-do.mat
                load ps_plot_v-do.mat;
                loaded_ps_ts = load('ps_plot_ts_v-do.mat');
                new_days_name = 'day_var';
                eval([new_days_name ' = loaded_ps_ts.day;']);
                load('ps_plot_ts_v-do.mat', 'bperp', 'ifg_list', 'lambda', 'lonlat', 'master_day', 'n_ps', 'ph_mm', 'ref_ps', 'unwrap_ifg_index');
            end
            % Include all PS (was: ismember against user-clicked lon2/lat2)
            ind = true(size(lonlat,1),1);
            displ = ph_disp(ind);
            disp_ts = ph_mm(ind,:);

            time_days = ((transpose(day_var))-time_zero);  % time and displacement vector with master
            time_master = master_day - time_zero;
            for i=1:length(time_days)
                if time_days(i) < time_master
                    disp_ts_temp(:,i) = disp_ts(:,i);
                    time_days_temp(i) = time_days(i);
                    n = i;
                else
                    disp_ts_temp(:,n+1) = zeros(size(disp_ts,1),1);
                    time_days_temp(n+1) = time_master;
                    disp_ts_temp(:,i+1) = disp_ts(:,i);
                    time_days_temp(i+1) = time_days(i);
                end
            end
            disp_ts = disp_ts_temp;
            clear disp_ts_temp
            time_days = time_days_temp;
            clear time_days_temp

            export_res = [lonlat(ind,1) lonlat(ind,2) displ disp_ts];

            % TABLE CREATION AND EXPORT
            point = (1:size(export_res, 1))';  % export first part of the table
            lon = export_res(:,1);
            lat = export_res(:,2);
            vel = export_res(:,3);
            infos_points = table(point, lon, lat, vel);
            writetable(infos_points, strcat(cd_fullpath, '/EXPORT/', export_name, '.xlsx'), 'Range', 'A2:D500000');
            save('PS_index.mat', 'ind');

            daily_displ = export_res(:,4:end);  % export second part of the table
            table_p2 = [time_days; daily_displ];
            displacements = table(table_p2);
            writetable(displacements, strcat(cd_fullpath, '/EXPORT/', export_name, '.xlsx'), 'Range', 'E1');

            displ_table_all = readtable(strcat('./EXPORT/', export_name, '.xlsx'));
            writetable(displ_table_all, strcat('./EXPORT/', export_name, '.csv'), 'WriteMode', 'overwrite');

            updateOutput(app, '----------------------- STEP 3: Displacement time series export finished -----------------------');

        elseif contains(ph_output, 'wrapped')

            updateOutput(app, '----------------------- STEP 3: Displacement time series export started -----------------------');

            load psver.mat

            psinfo_name = strcat('./ps', num2str(psver), '.mat');
            phase_name = strcat('./rc', num2str(psver), '.mat');

            loaded_day = load(psinfo_name, 'day');   % load the day variable and name change
            new_days_name_w = 'day_var_w';
            eval([new_days_name_w ' = loaded_day.day;']);

            load(psinfo_name, 'lonlat');       % load the lonlat variable
            load(psinfo_name, 'master_day');   % load the master_day variable
            load(phase_name);                  % load the variable with the phase values

            ph_all = ph_rc;         % wrapped complex phase for all PSs
            ph_w = angle(ph_all);   % wrapped phase for all PSs

            % Find PSs inside the given radius
            radius_size_deg = ref_radius_w / (111300 * cosd(ref_centre_lonlat_w(2)));                                   % Convert radius from meters to degrees (approximate conversion)
            distances_w = sqrt((lonlat(:,1) - ref_centre_lonlat_w(1)).^2 + (lonlat(:,2) - ref_centre_lonlat_w(2)).^2);   % Calculate distances between each point and the reference center
            indices_w = find(distances_w <= radius_size_deg);                                                            % Find indices of points inside the buffer
            ph_w_ts = ph_w(indices_w,:);

            % Data preparation for export
            time_days = ((transpose(day_var_w))-time_zero);  % time and displacement vector with master
            % time_master = master_day - time_zero;
            % for i=1:length(time_days)
            %     if time_days(i) < time_master
            %         ph_w_ts_temp(:,i) = ph_w_ts(:,i);
            %         time_days_temp(i) = time_days(i);
            %         n = i;
            %     else
            %         ph_w_ts_temp(:,n+1) = zeros(size(ph_w_ts,1),1);
            %         time_days_temp(n+1) = time_master;
            %         ph_w_ts_temp(:,i+1) = ph_w_ts(:,i);
            %         time_days_temp(i+1) = time_days(i);
            %     end
            % end
            % ph_w_ts = ph_w_ts_temp;
            % clear ph_w_ts_temp
            % time_days = time_days_temp;
            % clear time_days_temp

            export_res = [lonlat(indices_w,1) lonlat(indices_w,2) ph_w_ts];

            % TABLE CREATION AND EXPORT
            point = (1:size(export_res, 1))';  % export first part of the table
            lon = export_res(:,1);
            lat = export_res(:,2);
            infos_points = table(point, lon, lat);
            writetable(infos_points, strcat(cd_fullpath, '/EXPORT/', export_name, '_phW.xlsx'), 'Range', 'A2:C500000');

            daily_displ = export_res(:,3:end);  % export second part of the table
            table_p2 = [time_days; daily_displ];
            displacements = table(table_p2);
            writetable(displacements, strcat(cd_fullpath, '/EXPORT/', export_name, '_phW.xlsx'), 'Range', 'D1');

            displ_table_all = readtable(strcat('./EXPORT/', export_name, '_phW.xlsx'));
            writetable(displ_table_all, strcat('./EXPORT/', export_name, '_phW.csv'), 'WriteMode', 'overwrite');

            updateOutput(app, '----------------------- STEP 3: Displacement time series export finished -----------------------');

        end



        %% Atmospheric delay export intentionally omitted.

        %% ----------------------------------------------------

        % Display a message when the script is done
        updateOutput(app, 'StaMPS processing completed.');
        result.ok = true;
        result.message = 'StaMPS processing completed.';

        % Change lamp color to green (success)
        app.PreprocessingstatusLamp.Color = [0, 1, 0]; % Green

        % Offer to open the TS picker right away. Reaches the
        % picker via the existing OpenTSPickerButtonPushed
        % callback (workdir resolution, auto-gen of
        % ps_plot_ts_<vt>.mat, Mapping Toolbox check are all
        % handled there). Wrapped in try/catch so an older MATLAB
        % without uiconfirm still completes the Start cleanly.
        try
            full_export_name = app.FilenameEditField.Value;
        catch
            full_export_name = 'output';
        end
        try
            choice = uiconfirm(app.UIFigure, ...
                ['StaMPS processing completed.' newline newline ...
                 'A complete export has been written automatically to the ' ...
                 '''EXPORT/'' folder (' full_export_name '.xlsx and .csv), ' ...
                 'containing every PS with its full displacement time-series.' newline newline ...
                 'Open the interactive TS picker now to also extract per-point ' ...
                 'CSV time-series for a subset of points of interest? Each ' ...
                 'selected point will be saved as EXPORT/' full_export_name ...
                 '_<id>.csv.' newline newline ...
                 'You can always open the picker later from the ''TS Points'' tab.'], ...
                'Open TS picker', ...
                'Options', {'Open now', 'Open later'}, ...
                'DefaultOption', 1, 'CancelOption', 2);
        catch
            choice = 'Open later';
        end
        if strcmp(choice, 'Open now')
            try
                app.TabGroup.SelectedTab = app.TSPointsTab;
            catch
                % TabGroup property may have a different name in
                % future layouts; the picker still works from the
                % button if the user navigates manually.
            end
            try
                OpenTSPickerButtonPushed(app, []);
            catch ME
                uialert(app.UIFigure, ...
                    ['Auto-launch of TS picker failed: ' ME.message newline ...
                     'Click ''Load TS picker into this tab'' on the TS Points tab to retry.'], ...
                    'TS picker auto-launch failed');
            end
        end

    catch ME
        result.ok = false;
        result.message = ME.message;
        result.identifier = ME.identifier;

        % Restore the working directory to the StaMPS folder so a
        % subsequent Start run doesn't inherit a stale pwd of e.g.
        % .../PATCH_1 (stamps.m cd's into PATCH_<i> and only restores
        % on the happy path; if anything throws mid-loop, pwd stays
        % there). cd_fullpath was captured at the top of the run.
        try
            if exist('cd_fullpath', 'var') && ~isempty(cd_fullpath) && isfolder(cd_fullpath)
                cd(cd_fullpath);
            end
        catch
        end

        % Persist the complete stack trace.  The UI previously showed only
        % ME.message, which made a Windows native-tool failure impossible to
        % distinguish from a MATLAB/StaMPS source mismatch.
        try
            phase_error_report = getReport(ME, 'extended', 'hyperlinks', 'off');
            fprintf(2, '\n%s\n', phase_error_report);
            phase_error_log = fullfile(pwd, 'PHASE_StaMPS_error.log');
            phase_error_fid = fopen(phase_error_log, 'w');
            if phase_error_fid ~= -1
                fprintf(phase_error_fid, '%s\n', phase_error_report);
                fclose(phase_error_fid);
            end
        catch
            phase_error_log = '';
        end

        % If an error occurs
        if isempty(ME.identifier)
            updateOutput(app, ['An error occurred during script execution: ' ME.message]);
        else
            updateOutput(app, ['An error occurred during script execution [' ME.identifier ']: ' ME.message]);
        end
        if ~isempty(phase_error_log)
            updateOutput(app, ['Full error report saved to: ' phase_error_log]);
        else
            updateOutput(app, 'Please check each step log file!');
        end

        % Change lamp color to red (error)
        app.PreprocessingstatusLamp.Color = [1, 0, 0]; % Red

    end
end


function updateOutput(app, message)
app.log(message);
end

function OpenTSPickerButtonPushed(app, ~)
app.openTsPicker();
end

function restoreWorkDir(workDir)
try
    if isfolder(workDir), cd(workDir); end
catch
end
end
