function schema = schema()
%SCHEMA Visible metadata for the standalone PHASE Model interface.

schema.version = '6.0.0';
schema.groups = [
    group('project','Project','Inputs','Time-series source and execution environment')
    group('aoi','Area of interest','Selection','Shapefile or geographic bounding box')
    group('processing','Model design','Configuration','Dimension, processing family and spatial resolution')
    group('observations','Observations','Parameters','Noise, coherence and collocation settings')
    group('splines','Temporal model','Parameters','Spline selection, regularisation and atmospheric terms')
    group('spatial1d','One-dimensional model','Advanced','Covariance and deterministic controls for linear assets')
    group('spatial2d','Two-dimensional model','Advanced','Covariance and deterministic controls for areal domains')
    group('export','Outputs','Configuration','Interpolation and query-point exports')
];

schema.fields = [
    field('filepathIN','Displacement time-series file','path','project', ...
        'PHASE Module 1B XLSX or compatible CSV.','file',{}, {},'')
    field('pythonPath','Python installation','path','project', ...
        'Python used to format the Excel report.','file',{}, {},'')
    field('t0IN','First displacement date','date','project', ...
        'Reference date of the first displacement epoch.','',{}, {},'')
    field('flag_ouputDir','Remove existing output folders','boolean','project', ...
        'Delete previous PHASE Model output folders before processing.','',{}, {},'')
    field('markerSize','Plot marker size','number','project', ...
        'Marker size used by generated figures.','',{}, {},'pt')

    field('flag_AOIbb','Use geographic bounding box','boolean','aoi', ...
        'When disabled, PHASE uses the selected shapefile.','',{}, {},'')
    field('filepathAOI','AOI shapefile','path','aoi', ...
        'Polygon shapefile used to select persistent scatterers.','shapefile',{}, {},'')
    field('lonMinAOI','Minimum longitude','number','aoi','Western AOI bound.','',{}, {},'°')
    field('lonMaxAOI','Maximum longitude','number','aoi','Eastern AOI bound.','',{}, {},'°')
    field('latMinAOI','Minimum latitude','number','aoi','Southern AOI bound.','',{}, {},'°')
    field('latMaxAOI','Maximum latitude','number','aoi','Northern AOI bound.','',{}, {},'°')

    field('projDim','Project dimension','select','processing', ...
        'Choose a linear 1D asset or a 2D areal domain.','', ...
        {'1D','2D'},{'1D — linear asset','2D — areal domain'},'')
    field('procType','Processing family','select','processing', ...
        'Temporal, deterministic or stochastic modelling workflow.','', ...
        {'temporal','temporal&NNI','spatialDET','spatialSTC'}, ...
        {'Temporal','Temporal + NNI','Spatio-temporal deterministic','Spatio-temporal stochastic'},'')
    field('minMonths','Minimum period for outlier detection','number','processing', ...
        'Minimum time span used by spline outlier filtering.','',{}, {},'months')
    field('cline_resolution','Centerline resolution','number','processing', ...
        'Sampling resolution for 1D projects.','',{}, {},'m')
    field('grid_resolution','Grid resolution','number','processing', ...
        'Sampling resolution for 2D projects.','',{}, {},'m')
    field('step_t_ST','Temporal step','number','processing', ...
        'Temporal sampling step for spatio-temporal models.','',{}, {},'epochs')

    field('varNoise_method','A-priori variance','select','observations', ...
        'Estimate automatically, enter manually or derive from coherence.','', ...
        {'auto','manual','coherence'},{'Automatic','Manual','From coherence'},'')
    field('varNoise_manual','Manual variance','number','observations', ...
        'A-priori observation variance when manual mode is selected.','',{}, {},'mm²')
    field('coherence_dir','Coherence folder','path','observations', ...
        'Folder containing coherence products.','folder',{}, {},'')
    field('constellation','SAR constellation','select','observations','', '', ...
        {'Sentinel-1','COSMO-SkyMed'},{'Sentinel-1','COSMO-SkyMed'},'')
    field('num_looks','Number of looks','number','observations', ...
        'Equivalent looks used for coherence-derived variance.','',{}, {},'')
    field('coll_proc','Collocation approach','select','observations','', '', ...
        {'filtering','prediction'},{'Filtering','Prediction'},'')
    field('coll_step_est','Prediction step','number','observations', ...
        'Estimation step used by collocation prediction.','',{}, {},'m')
    field('min_coll_snr_method','Minimum collocation SNR','select','observations', ...
        'Use the ModellingInTime default or enter a manual threshold.','', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('min_coll_snr','Manual minimum SNR','number','observations', ...
        'Minimum residual signal-to-noise ratio required for collocation.','',{}, {},'')
    field('min_coll_corr_samples_method','Minimum correlation length','select','observations', ...
        'Use the ModellingInTime default or enter a manual threshold.','', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('min_coll_corr_samples','Manual correlation length','number','observations', ...
        'Minimum correlation length expressed in median sampling intervals.','',{}, {},'samples')

    field('num_spl_method','Number of temporal splines','select','splines','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('spline_method','Automatic spline criterion','select','splines','', '', ...
        {'MDL','variance','F_test','chi2_test'},{'MDL','Variance','F test','Chi-square test'},'')
    field('num_spl_manual','Manual temporal splines','number','splines','', '',{}, {},'')
    field('lambda_method','Spline regularisation','select','splines','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('lambda_manual','Manual lambda','number','splines','', '',{}, {},'')
    field('min_period_days_method','Minimum Fourier period','select','splines', ...
        'Use the ModellingInTime default or enter a manual threshold.','', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('min_period_days','Manual Fourier period','number','splines', ...
        'Shortest Fourier period retained in the temporal model.','',{}, {},'days')
    field('spline_min_knot_intervals_method','Minimum spline knot spacing','select','splines', ...
        'Use the ModellingInTime default or enter a manual threshold.','', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('spline_min_knot_intervals','Manual knot spacing','number','splines', ...
        'Minimum knot spacing in median sampling intervals.','',{}, {},'intervals')
    field('spline_max_fraction_method','Maximum spline fraction','select','splines', ...
        'Use the ModellingInTime default or enter a manual threshold.','', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('spline_max_fraction','Manual spline fraction','number','splines', ...
        'Maximum spline count as a fraction of the observations.','',{}, {},'0–0.5')
    field('detrendMethod','Residual atmospheric artifacts','select','splines','', '', ...
        {'cleanObs','residualAtm'},{'No additional plane','Estimate residual planes'},'')
    field('polyDegreeST','Polynomial maximum degree','select','splines','', '', ...
        {'1','2','3'},{'1','2','3'},'')
    field('useInclinedMeansST','Tilted epoch-wise planes','boolean','splines','', '',{}, {},'')

    field('dtCov_method_STC1D','1D temporal covariance bin','select','spatial1d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('dtCov_STC1D','Manual temporal covariance bin','number','spatial1d','', '',{}, {},'days')
    field('dsCov_method_STC1D','1D spatial covariance bin','select','spatial1d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('dsCov_STC1D','Manual spatial covariance bin','number','spatial1d','', '',{}, {},'m')
    field('tCovModel_STC1D','1D temporal covariance model','select','spatial1d','', '', ...
        {'gaussian','gaussian+cosine','exponential'}, ...
        {'Gaussian','Gaussian + cosine','Exponential'},'')
    field('sCovModel_STC1D','1D spatial covariance model','select','spatial1d','', '', ...
        {'gaussian','gaussian+cosine','exponential'}, ...
        {'Gaussian','Gaussian + cosine','Exponential'},'')
    field('varNoise_DET1D','1D deterministic noise','select','spatial1d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('varNoise_manual_DET1D','1D manual noise','number','spatial1d','', '',{}, {},'mm²')
    field('num_spl_method_DET1D','1D deterministic splines','select','spatial1d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('spline_method_DET1D','1D spline criterion','select','spatial1d','', '', ...
        {'MDL','variance','F_test','chi2_test'},{'MDL','Variance','F test','Chi-square test'},'')
    field('num_spl_row_manual_DET1D','1D row splines','number','spatial1d','', '',{}, {},'')
    field('num_spl_col_manual_DET1D','1D column splines','number','spatial1d','', '',{}, {},'')
    field('lambda_method_DET1D','1D regularisation','select','spatial1d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('lambda_manual_DET1D','1D manual lambda','number','spatial1d','', '',{}, {},'')

    field('dtCov_method_STC2D','2D temporal covariance bin','select','spatial2d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('dtCov_STC2D','Manual temporal covariance bin','number','spatial2d','', '',{}, {},'days')
    field('dsCov_method_STC2D','2D spatial covariance bin','select','spatial2d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('dsCov_STC2D','Manual spatial covariance bin','number','spatial2d','', '',{}, {},'m')
    field('tCovModel_STC2D','2D temporal covariance model','select','spatial2d','', '', ...
        {'gaussian','gaussian+cosine','exponential'}, ...
        {'Gaussian','Gaussian + cosine','Exponential'},'')
    field('sCovModel_STC2D','2D spatial covariance model','select','spatial2d','', '', ...
        {'gaussian','gaussian+cosine','exponential'}, ...
        {'Gaussian','Gaussian + cosine','Exponential'},'')
    field('varNoise_DET2D','2D deterministic noise','select','spatial2d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('varNoise_manual_DET2D','2D manual noise','number','spatial2d','', '',{}, {},'mm²')
    field('num_spl_method_DET2D','2D deterministic splines','select','spatial2d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('spline_method_DET2D','2D spline criterion','select','spatial2d','', '', ...
        {'MDL','variance','F_test','chi2_test'},{'MDL','Variance','F test','Chi-square test'},'')
    field('num_spl_row_manual_DET2D','2D row splines','number','spatial2d','', '',{}, {},'')
    field('num_spl_col_manual_DET2D','2D column splines','number','spatial2d','', '',{}, {},'')
    field('num_spl_t_manual_DET2D','2D temporal splines','number','spatial2d','', '',{}, {},'')
    field('lambda_method_DET2D','2D regularisation','select','spatial2d','', '', ...
        {'auto','manual'},{'Automatic','Manual'},'')
    field('lambda_manual_DET2D','2D manual lambda','number','spatial2d','', '',{}, {},'')

    field('flag_PSinterp','Export interpolated PS observations','boolean','export','', '',{}, {},'')
    field('flag_tsExtr','Interpolate query-point time series','boolean','export','', '',{}, {},'')
    field('filepath_EXTR','Query-points file','path','export', ...
        'Text file containing query coordinates.','query',{}, {},'')
];
end

function value = group(id,title,kicker,subtitle)
value = struct('id',id,'title',title,'kicker',kicker,'subtitle',subtitle);
end

function value = field(id,label,type,groupId,description,browse,options,labels,unit)
value = struct( ...
    'id',id,'label',label,'type',type,'group',groupId, ...
    'description',description,'browse',browse, ...
    'options',{options},'optionLabels',{labels},'unit',unit);
end
