function out = schema()
%SCHEMA Metadata for the preprocessing beta interface.

items = repmat(item('', '', '', '', '', '', {}, false, 'both'), 0, 1);
items(end+1) = item('constellation','Satellite constellation','images','choice','', ...
    'Choose the acquisition family to configure and process.', {'Sentinel-1','COSMO-SkyMed'}, false, 'both');
items(end+1) = item('python','Python executable or environment','setup','text','', ...
    'Installer-detected Python executable, environment name or command.', {}, false, 'both');
items(end+1) = item('gptbin_path','SNAP gpt executable','setup','path','', ...
    'Full path to the SNAP gpt executable or bin location.', {}, false, 'both');
items(end+1) = item('update_processed_data','Update an existing processed stack','images','toggle','', ...
    'Sentinel-1 only. Search and append acquisitions after the latest local date.', {}, false, 'SEN');

items(end+1) = item('lon_min','Minimum longitude','aoi','number','deg','Western AOI boundary.',{},false,'both');
items(end+1) = item('lon_max','Maximum longitude','aoi','number','deg','Eastern AOI boundary.',{},false,'both');
items(end+1) = item('lat_min','Minimum latitude','aoi','number','deg','Southern AOI boundary.',{},false,'both');
items(end+1) = item('lat_max','Maximum latitude','aoi','number','deg','Northern AOI boundary.',{},false,'both');

items(end+1) = item('auto_master','Select master automatically','master','toggle','', ...
    'Let the preprocessing scripts select the optimal reference acquisition.',{},false,'both');
items(end+1) = item('master_date','Manual master date','master','text','YYYYMMDD', ...
    'Used only when automatic master selection is disabled.',{},false,'both');
items(end+1) = item('process_master','Process the master image','master','toggle','', ...
    'Disable only when valid master products already exist.',{},false,'both');
items(end+1) = item('polarisation','Polarisation','master','choice','', ...
    'Sentinel-1 polarisation used throughout the stack.',{'VV','VH','HH'},false,'SEN');

demOptions = {'SRTM 1Sec HGT','SRTM 3Sec','Copernicus 30m Global DEM', ...
    'Copernicus 90m Global DEM','CDEM','GETASSE30','External DEM'};
items(end+1) = item('first_step','First preprocessing step','slaves','choice','', ...
    'Resume from this step when the products required by earlier steps already exist.', ...
    {'1 — Prepare slave acquisitions', ...
     '2 — Split or subset slave products', ...
     '3 — Coregister and form interferograms', ...
     '4 — Export the stack to StaMPS', ...
     '5 — Generate average intensity', ...
     '6 — Terrain-correct optional products'},false,'both');
items(end+1) = item('dem_name','Interferogram DEM','slaves','choice','', ...
    'Elevation model used for interferogram generation.',demOptions,false,'both');
items(end+1) = item('dem_file','External interferogram DEM','slaves','path','', ...
    'GeoTIFF path required only when External DEM is selected.',{},false,'both');
items(end+1) = item('dem_name_coreg','Coregistration DEM','slaves','choice','', ...
    'Sentinel-1 elevation model used during coregistration.',demOptions,false,'SEN');
items(end+1) = item('dem_file_coreg','External coregistration DEM','slaves','path','', ...
    'GeoTIFF path required only when External DEM is selected.',{},false,'SEN');
items(end+1) = item('dem_resampling','DEM resampling','slaves','choice','', ...
    'Sentinel-1 DEM interpolation method.',{'NEAREST_NEIGHBOUR','BILINEAR_INTERPOLATION','CUBIC_CONVOLUTION', ...
    'BISINC_5_POINT_INTERPOLATION','BISINC_11_POINT_INTERPOLATION','BISINC_21_POINT_INTERPOLATION','BICUBIC_INTERPOLATION'},true,'SEN');
items(end+1) = item('num_gcp','Coregistration GCP count','slaves','number','', ...
    'COSMO-SkyMed ground control points.',{},false,'CSK');
items(end+1) = item('remove_slaves_after_processing','Remove downloaded source images','slaves','toggle','', ...
    'After a successful export, delete the original ZIP/HDF5 files in slaves. This is not an intermediate-product cleanup.',{},false,'both');
items(end+1) = item('remove_split_after_processing','Remove split/subset products','slaves','toggle','', ...
    'Delete the SNAP split (Sentinel-1) or subset (COSMO-SkyMed) folder after successful preprocessing.',{},true,'both');
items(end+1) = item('remove_coreg_after_processing','Remove coregistered products','slaves','toggle','', ...
    'Delete the SNAP coreg folder after successful preprocessing. Step 3 cannot be resumed without recreating it.',{},true,'both');
items(end+1) = item('remove_ifg_after_processing','Remove interferogram products','slaves','toggle','', ...
    'Delete the SNAP ifg folder after successful preprocessing. Step 4 cannot be resumed without recreating it.',{},true,'both');

items(end+1) = item('auto_epsg','Estimate projected CRS from AOI','products','toggle','', ...
    'Use the AOI centre to select a local UTM CRS, with polar stereographic fallbacks.',{},false,'both');
items(end+1) = item('epsg_code','Output EPSG code','products','number','', ...
    'Projected coordinate reference system used by the correctly warped output rasters.',{},false,'both');
items(end+1) = item('generate_coherence','Generate terrain-corrected coherence','products','toggle','', ...
    'Keep the terrain-corrected coherence GeoTIFF products.',{},false,'both');
items(end+1) = item('generate_lia','Generate local incidence angle','products','toggle','', ...
    'Keep the terrain-corrected local incidence angle GeoTIFF products.',{},false,'both');

items(end+1) = item('cpu','Processing cores','setup','number','cores', ...
    'Number of CPU cores passed to SNAP.',{},false,'both');
items(end+1) = item('cache','SNAP cache','setup','text','', ...
    'RAM cache passed to SNAP, for example 26G.',{},false,'both');

groups = struct( ...
    'id', {'images','setup','aoi','master','slaves','products'}, ...
    'title', {'Download / import images','Setup & resources','Area of interest','Master processing','Slave processing','Output products'}, ...
    'subtitle', { ...
        'Import acquisitions, download Sentinel-1 data and update an existing stack', ...
        'Python, SNAP executable paths, CPU and memory allocation', ...
        'Geographic boundaries shared by search and processing', ...
        'Reference acquisition selection and preparation', ...
        'Resume point, DEMs and explicit disk cleanup', ...
        'Automatic CRS selection and independently controlled products'});
out = struct('groups', groups, 'items', items);
end

function s = item(id, label, group, type, unit, help, options, advanced, appliesTo)
s = struct('id', id, 'label', label, 'group', group, 'type', type, ...
    'unit', unit, 'help', help, 'options', {options}, 'advanced', advanced, ...
    'appliesTo', appliesTo);
end
