"""Extract the proven PHASE_StaMPS Start callback into an editable .m file.

This intentionally preserves the stable processing logic byte-for-byte apart
from the function wrapper, result reporting, working directory setup and two
small adapter functions. It lets the beta replace App Designer without also
rewriting the scientific workflow in the same change.
"""

from pathlib import Path
import zipfile


ROOT = Path(__file__).resolve().parents[1]
MLAPP = ROOT / "PHASE_Preprocessing" / "PHASE_StaMPS.mlapp"
OUTPUT = (
    ROOT
    / "PHASE_Preprocessing"
    / "+phase_stamps_beta"
    / "runProcessing.m"
)


def _replace_checked(text: str, old: str, new: str, expected: int) -> str:
    count = text.count(old)
    if count != expected:
        raise RuntimeError(
            f"Expected {expected} StaMPS anchor(s), found {count}: {old!r}"
        )
    return text.replace(old, new)


def extract(xml: str) -> str:
    start = xml.index("        function StartButtonPushed(app, event)")
    end = xml.index("        % Button pushed function: LoadButton", start)
    callback = xml[start:end].rstrip()
    closing = "        end"
    if not callback.endswith(closing):
        raise RuntimeError("Start callback does not end at the expected indentation")
    callback = callback[: -len(closing)].rstrip() + "\n"
    # Every class member starts eight spaces in App Designer. Do not use
    # textwrap.dedent: multi-line MATLAB character literals can legitimately
    # start in column zero and would prevent it from removing class indent.
    callback = "\n".join(
        (line[8:] if line.startswith("        ") else line).rstrip()
        for line in callback.splitlines()
    ) + "\n"
    callback = callback.replace(
        "function StartButtonPushed(app, event)\n",
        "function result = runProcessing(app)\n",
        1,
    )

    setup = """\
%RUNPROCESSING Stable PHASE StaMPS engine extracted from PHASE_StaMPS.mlapp.
% Generated by tools/extract_stamps_beta_backend.py. Edit the stable callback
% first and regenerate, or deliberately remove the generated notice when the
% beta engine is split into independent processing services.

result = struct('ok', false, 'message', '', 'identifier', '');
if ~isfolder(app.WorkDir)
    error('PHASE_StaMPS_beta:workDirMissing', ...
        'StaMPS processing folder does not exist: %s', app.WorkDir);
end
cd(app.WorkDir);
workDirCleanup = onCleanup(@() restoreWorkDir(app.WorkDir)); %#ok<NASGU>

"""
    callback = callback.replace(
        "function result = runProcessing(app)\n",
        "function result = runProcessing(app)\n" + setup,
        1,
    )
    callback = callback.replace(
        "        clc;\n",
        "        % Keep the Command Window history; the beta has its own live log.\n",
        1,
    )
    callback = _replace_checked(
        callback,
        "'select_method', 'percent_rand', 'weed_standard_dev'",
        "'select_method', 'percent_rand', 'density_rand', 'weed_standard_dev'",
        1,
    )
    callback = _replace_checked(
        callback,
        "        setparm('percent_rand', percent_rand); % maximum acceptable percentage, alternative 'density_rand'",
        """\
        if strcmpi(select_method, 'DENSITY')
            setparm('density_rand', density_rand); % maximum random PS density
        else
            setparm('percent_rand', percent_rand); % maximum acceptable percentage, alternative 'density_rand'
        end""",
        1,
    )

    # Execute PHASE-owned shell commands through Java ProcessBuilder so
    # Windows never flashes cmd.exe windows and output is streamed to the
    # Run monitor. Native commands launched internally by the maintained
    # StaMPS fork inherit the same non-interactive MATLAB session.
    mt_prep_system = (
        "mt_prep_snap_status = system([which('mt_prep_snap.bat') ' ' "
        "master_date ' ' s2s_export_path ' ' amplitude_threshold]);"
    )
    mt_prep_hidden = """\
[mt_prep_snap_status, mt_prep_snap_output] = ...
    phase_stamps_beta.runCommandHidden(app, ...
        {which('mt_prep_snap.bat'), master_date, s2s_export_path, amplitude_threshold}, ...
        'StaMPS data preparation');
"""
    callback = _replace_checked(
        callback, mt_prep_system, mt_prep_hidden.rstrip(), 2
    )
    callback = _replace_checked(
        callback,
        "Check the Command Window above for the cause",
        "Check the PHASE Run monitor above for the cause",
        2,
    )
    for shell_command, label in (
        (
            "system(strjoin({source_stamps, source_train, source_snap}, ';'));",
            "StaMPS, TRAIN and SNAP environment preparation",
        ),
        (
            "system(strjoin({source_stamps, source_snap}, ';'));",
            "StaMPS and SNAP environment preparation",
        ),
        (
            "system(strjoin({source_stamps, source_train}, ';'));",
            "StaMPS and TRAIN environment preparation",
        ),
        (
            "system(source_stamps);",
            "StaMPS environment preparation",
        ),
    ):
        callback = _replace_checked(
            callback,
            shell_command,
            f"phase_stamps_beta.runCommandHidden(app, "
            f"{shell_command[len('system('):-2]}, '{label}');",
            1,
        )
    callback = _replace_checked(
        callback,
        "[snaphu_status, snaphu_where] = dos('where snaphu');",
        "[snaphu_status, snaphu_where] = phase_stamps_beta.runCommandHidden( ...\n"
        "                    app, {'where','snaphu'}, 'snaphu lookup');",
        1,
    )
    callback = _replace_checked(
        callback,
        "progress is printed in the MATLAB Command Window as ",
        "progress is mirrored live in the PHASE Run monitor as ",
        1,
    )
    success_anchor = """\
        % Display a message when the script is done
        updateOutput(app, 'StaMPS processing completed.');

        % Change lamp color to green (success)
"""
    success_new = """\
        % Display a message when the script is done
        updateOutput(app, 'StaMPS processing completed.');
        result.ok = true;
        result.message = 'StaMPS processing completed.';

        % Change lamp color to green (success)
"""
    if callback.count(success_anchor) != 1:
        raise RuntimeError("Could not locate stable processing success anchor")
    callback = callback.replace(success_anchor, success_new, 1)

    catch_anchor = """\
    catch ME

        % Restore the working directory to the StaMPS folder so a
"""
    catch_new = """\
    catch ME
        result.ok = false;
        result.message = ME.message;
        result.identifier = ME.identifier;

        % Restore the working directory to the StaMPS folder so a
"""
    if callback.count(catch_anchor) != 1:
        raise RuntimeError("Could not locate outer processing catch block")
    callback = callback.replace(catch_anchor, catch_new, 1)

    helpers = """

function updateOutput(app, message)
app.log(message);
end

function OpenTSPickerButtonPushed(app, ~)
app.openTsPicker();
end

function restoreWorkDir(workDir)
try
    if isfolder(workDir), cd(workDir); end
catch
end
end
"""
    return callback.rstrip() + "\nend\n" + helpers


def main() -> None:
    with zipfile.ZipFile(MLAPP) as archive:
        xml = archive.read("matlab/document.xml").decode("utf-8")
    OUTPUT.write_text(extract(xml), encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
